enum AppPermission {
  courseCreate('academics:course:create'),
  courseRead('academics:course:read'),
  courseUpdate('academics:course:update'),
  courseDelete('academics:course:update'),
  timetableRead('academics:timetable:read'),
  timetableCreate('academics:timetable:create'),
  timetableUpdate('academics:timetable:update'),
  timetableDelete('academics:timetable:delete'),
  departmentRead('academics:department:read'),
  studentGroupRead('academics:student-group:read'),
  studentGroupCreate('academics:student-group:create'),
  studentGroupUpdate('academics:student-group:update'),
  studentGroupDelete('academics:student-group:delete'),
  patientCaseSheetRead('clinical:patient-case-sheet:read'),
  patientCaseSheetCreate('clinical:patient-case-sheet:create'),
  patientCaseSheetUpdate('clinical:patient-case-sheet:update'),
  patientCaseSheetDelete('clinical:patient-case-sheet:delete'),
  caseSheetTemplateRead('clinical:case-sheet-template:read'),
  encounterRead('encounter:encounter:read'),
  encounterClaimOrUnclaim('encounter:encounter:update'),
  treatmentScheduleCreate('clinical:treatment-schedule:create'),
  treatmentScheduleRead('clinical:treatment-schedule:read'),
  treatmentScheduleUpdate('clinical:treatment-schedule:update'),
  treatmentScheduleDelete('clinical:treatment-schedule:delete'),
  labShadeGuidesRead('clinical:lab-shade-guides:read'),
  labShadeGuidesCreate('clinical:lab-shade-guides:create'),
  labShadeGuidesUpdate('clinical:lab-shade-guides:update'),
  cervicalShadesRead('clinical:cervical-shade:read'),
  cervicalShadesCreate('clinical:cervical-shade:create'),
  cervicalShadesUpdate('clinical:cervical-shade:update'),
  middleShadesRead('clinical:middle-shade:read'),
  middleShadesCreate('clinical:middle-shade:create'),
  middleShadesUpdate('clinical:middle-shade:update'),
  incisalShadesRead('clinical:incisal-shade:read'),
  incisalShadesCreate('clinical:incisal-shade:create'),
  incisalShadesUpdate('clinical:incisal-shade:update');

  final String value;
  const AppPermission(this.value);
}
